### ISSUE TITLE
Low resolution simulation settings

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/DifferentiableHOS#9]
@dlanzieri I'm opening this thread to discuss what settings we want to use for low resolution simulations. We know they are not very accurate, but they will allow us to move forward with building the pipeline and our tools. 

I've opened a notebook here: https://github.com/LSSTDESC/DifferentiableHOS/blob/main/notebooks/Prototype_SRD_Y1.ipynb

This is meant to test some choices of noise levels and resolution against a kappa TNG example, and with some choices defined to match the DESC Science Requirements Document: https://arxiv.org/abs/1809.01669

At 10 gal per arcmin and a smoothing scale of 1 arcmin it already looks reasonable:
![image](https://user-images.githubusercontent.com/861591/120907128-6a25ff80-c65f-11eb-8008-3d9719618e9d.png)

Here is the power spectrum:
![image](https://user-images.githubusercontent.com/861591/120907138-76aa5800-c65f-11eb-8619-a9ebec0de1c8.png)

And peak counts:
![image](https://user-images.githubusercontent.com/861591/120907144-7e69fc80-c65f-11eb-9448-6851913065d5.png)

So obviously clusters are not as strong, due to our lack of resolution, but everything seems to be in the right ballpark probably good enough for development.

**Comment by dlanzieri** [comment]
@EiffL thank you for this! 
So, now we could investigate a bit more the choices of noise levels and resolution against a kappa TNG example to find the best match we can achieve, then, with the found setting we can run several simulations to compute the covariance matrix.

**Comment by EiffL** [comment]
Precisely :-) you can play around with the settings but I didn't see a huge improvement by changing the configuration a lot. If you want to proceed with these current settings I'm ok with it.

**Comment by EiffL** [comment]
@dlanzieri can you document here our final choice for the analysis, and if there is no need for further tuning here, we probably can close this issue

**Comment by dlanzieri** [comment]
Sure!
As described in the issue #10 we defined the settings we want to use for low resolution simulations after the implementation of the online PGD. 
Here our final choice:


```
"nc"= 128 ( Number of transverse voxels in the simulation volume)
"field_npix"=  1024 (Resolution of the convergence map)
"box_size"= 205. (Transverse comoving size of the simulation volume)
"field_size"= 5. (Size of the lensing field in degrees)
"n_lens"= 11  (Number of lensplanes in the lightcone)
"plane_resolution"= 2048 (Resolution of the lensplanes)
"sigma of the lensplanes" =1.024   (Smoothing  applied to the lensplanes)
"sigma_pix"= 1 arcmin (Smoothing applied to the convergence map)

```
